function vedios=configSeqs

CVPR2013={
%     struct('name','Soccer','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Soccer\','startFrame',1,'endFrame',392,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Matrix','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Matrix\','startFrame',1,'endFrame',100,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Ironman','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Ironman\','startFrame',1,'endFrame',166,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Deer','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Deer\','startFrame',1,'endFrame',71,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Skating1','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Skating1\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Shaking','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Shaking\','startFrame',1,'endFrame',365,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Singer1','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Singer1\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Singer2','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Singer2\','startFrame',1,'endFrame',366,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
      struct('name','CarDark','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\CarDark\','startFrame',1,'endFrame',393,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Car4','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Car4\','startFrame',1,'endFrame',659,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','David','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\David\','startFrame',300,'endFrame',770,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','David2','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\David2\','startFrame',1,'endFrame',537,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Sylvester','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Sylvester\','startFrame',1,'endFrame',1345,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Trellis','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Trellis\','startFrame',1,'endFrame',569,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Fish','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Fish\','startFrame',1,'endFrame',476,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Mhyang','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Mhyang\','startFrame',1,'endFrame',1490,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Coke','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Coke\','startFrame',1,'endFrame',291,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Bolt','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Bolt\','startFrame',1,'endFrame',350,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Boy','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Boy\','startFrame',1,'endFrame',602,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Dudek','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Dudek\','startFrame',1,'endFrame',1145,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Crossing','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Crossing\','startFrame',1,'endFrame',120,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Couple','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Couple\','startFrame',1,'endFrame',140,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Football1','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Football1\','startFrame',1,'endFrame',74,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%       struct('name','Jogging','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Jogging\','startFrame',1,'endFrame',307,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%       struct('name','Jogging-2','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Jogging\','startFrame',1,'endFrame',307,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Doll','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Doll\','startFrame',1,'endFrame',3872,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Girl','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Girl\','startFrame',1,'endFrame',500,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Walking2','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Walking2\','startFrame',1,'endFrame',500,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Walking','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Walking\','startFrame',1,'endFrame',412,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Fleetface','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Fleetface\','startFrame',1,'endFrame',707,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Freeman1','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Freeman1\','startFrame',1,'endFrame',326,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Freeman3','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Freeman3\','startFrame',1,'endFrame',460,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Freeman4','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Freeman4\','startFrame',1,'endFrame',283,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','David3','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\David3\','startFrame',1,'endFrame',252,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Jumping','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Jumping\','startFrame',1,'endFrame',313,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','CarScale','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\CarScale\','startFrame',1,'endFrame',252,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Skiing','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Skiing\','startFrame',1,'endFrame',81,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Dog1','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Dog1\','startFrame',1,'endFrame',1350,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Suv','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Suv\','startFrame',1,'endFrame',945,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','MotorRolling','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\MotorRolling\','startFrame',1,'endFrame',164,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','MountainBike','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\MountainBike\','startFrame',1,'endFrame',228,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Lemming','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Lemming\','startFrame',1,'endFrame',1336,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Liquor','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Liquor\','startFrame',1,'endFrame',1741,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Woman','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Woman\','startFrame',1,'endFrame',597,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Faceocc1','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Faceocc1\','startFrame',1,'endFrame',892,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Faceocc2','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Faceocc2\','startFrame',1,'endFrame',812,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Basketball','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Basketball\','startFrame',1,'endFrame',725,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Football','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Football\','startFrame',1,'endFrame',362,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Subway','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Subway\','startFrame',1,'endFrame',175,'nz',4,'ext','jpg','init_rect', [0 0 0 0]),...
%     struct('name','Tiger1','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Tiger1\','startFrame',1,'endFrame',354,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Tiger2','path','C:\Users\Admin\Desktop\Tracker_benchmark_data\OTB\Tiger2\','startFrame',1,'endFrame',365,'nz',4,'ext','jpg','init_rect', [0,0,0,0])
    };

% OTB50={
%      struct('name','Basketball','path','C:\Users\Admin\Desktop\OTB50\Basketball\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Biker','path','C:\Users\Admin\Desktop\OTB50\Biker\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Bird1','path','C:\Users\Admin\Desktop\OTB50\Bird1\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','BlurBody','path','C:\Users\Admin\Desktop\OTB50\BlurBody\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','BlurCar2','path','C:\Users\Admin\Desktop\OTB50\BlurCar2\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','BlurFace','path','C:\Users\Admin\Desktop\OTB50\BlurFace\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','BlurOwl','path','C:\Users\Admin\Desktop\OTB50\BlurOwl\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Bolt','path','C:\Users\Admin\Desktop\OTB50\Bolt\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Box','path','C:\Users\Admin\Desktop\OTB50\Box\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Car1','path','C:\Users\Admin\Desktop\OTB50\Car1\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Car4','path','C:\Users\Admin\Desktop\OTB50\Car4\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','CarDark','path','C:\Users\Admin\Desktop\OTB50\CarDark\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','CarScale','path','C:\Users\Admin\Desktop\OTB50\CarScale\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','ClifBar','path','C:\Users\Admin\Desktop\OTB50\ClifBar\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Couple','path','C:\Users\Admin\Desktop\OTB50\Couple\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Crowds','path','C:\Users\Admin\Desktop\OTB50\Crowds\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','David','path','C:\Users\Admin\Desktop\OTB50\David\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Deer','path','C:\Users\Admin\Desktop\OTB50\Deer\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Diving','path','C:\Users\Admin\Desktop\OTB50\Diving\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','DragonBaby','path','C:\Users\Admin\Desktop\OTB50\DragonBaby\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Dudek','path','C:\Users\Admin\Desktop\OTB50\Dudek\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Football','path','C:\Users\Admin\Desktop\OTB50\Football\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Freeman4','path','C:\Users\Admin\Desktop\OTB50\Freeman4\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Girl','path','C:\Users\Admin\Desktop\OTB50\Girl\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Human3','path','C:\Users\Admin\Desktop\OTB50\Human3\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Human4','path','C:\Users\Admin\Desktop\OTB50\Human4\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Human6','path','C:\Users\Admin\Desktop\OTB50\Human6\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Human9','path','C:\Users\Admin\Desktop\OTB50\Human9\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Ironman','path','C:\Users\Admin\Desktop\OTB50\Ironman\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Jump','path','C:\Users\Admin\Desktop\OTB50\Jump\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Jumping','path','C:\Users\Admin\Desktop\OTB50\Jumping\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Liquor','path','C:\Users\Admin\Desktop\OTB50\Liquor\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Matrix','path','C:\Users\Admin\Desktop\OTB50\Matrix\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','MotorRolling','path','C:\Users\Admin\Desktop\OTB50\MotorRolling\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Panda','path','C:\Users\Admin\Desktop\OTB50\Panda\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','RedTeam','path','C:\Users\Admin\Desktop\OTB50\RedTeam\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Shaking','path','C:\Users\Admin\Desktop\OTB50\Shaking\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Singer2','path','C:\Users\Admin\Desktop\OTB50\Singer2\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Skating1','path','C:\Users\Admin\Desktop\OTB50\Skating1\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Skating2','path','C:\Users\Admin\Desktop\OTB50\Skating2\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Skiing','path','C:\Users\Admin\Desktop\OTB50\Skiing\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Soccer','path','C:\Users\Admin\Desktop\OTB50\Soccer\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Surfer','path','C:\Users\Admin\Desktop\OTB50\Surfer\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Sylvester','path','C:\Users\Admin\Desktop\OTB50\Sylvester\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Tiger2','path','C:\Users\Admin\Desktop\OTB50\Tiger2\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Trellis','path','C:\Users\Admin\Desktop\OTB50\Trellis\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Walking','path','C:\Users\Admin\Desktop\OTB50\Walking\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Walking2','path','C:\Users\Admin\Desktop\OTB50\Walking2\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','Woman','path','C:\Users\Admin\Desktop\OTB50\Woman\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     };



% OTB100={
%     struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%      struct('name','','path','C:\Users\Admin\Desktop\OTB50\\','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     };

vedios=[CVPR2013];

